server:
  port: 8080

eureka:
  regist:
    host: localhost
    port: 8090
  client:
    serviceUrl:
      defaultZone: http://${eureka.regist.host}:${eureka.regist.port}/eureka/


spring:
  application:
    name: web
feign:
  hystrix:
    enabled: true
